AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  blockchain-apis

  Sample SAM Template for blockchain-apis

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  BitcoinFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        HelloBtc:
          Type: Api
          Properties:
            Path: /btc/hello
            Method: get
        Balance:
          Type: Api
          Properties:
            Path: /btc/balance
            Method: get
    Metadata:
      DockerTag: nodejs16.x-v1
      DockerContext: ./bitcoin
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/btc/hello/"
  BitcoinFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt BitcoinFunction.Arn
  BitcoinFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt BitcoinFunctionRole.Arn
